import 'package:flutter/material.dart';
import 'package:sos/shared/models/post.dart';

class ContentSection extends StatelessWidget {
  final Post post; // Use the Post class generated by freezed

  const ContentSection({super.key, required this.post});

  @override
  Widget build(BuildContext context) {
    return Text(
      post.content ?? '', // Use the content field from the Post class
      style: const TextStyle(fontSize: 16.0),
    );
  }
}
