import 'package:flutter/material.dart';
import 'package:sos/shared/models/post.dart';

class ContentSection extends StatelessWidget {
  final Post post; // Use the Post class generated by freezed

  const ContentSection({super.key, required this.post});

  @override
  Widget build(BuildContext context) {
    // Check if the content is null or empty
    if (post.content == null || post.content!.isEmpty) {
      return const SizedBox.shrink(); // If empty, return an empty widget
    }

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 15.0),
      alignment: Alignment.center,
      child: SizedBox(
        child: Text(
          post.content!,
          style: const TextStyle(
            color: Colors.black,
            fontSize: 16,
            fontFamily: 'Apple SD Gothic Neo',
            fontWeight: FontWeight.w400,
            height: 1.2,
          ),
        ),
      ),
    );
  }
}
