import 'package:flutter/material.dart';
import 'package:sos/shared/models/post.dart';

class ImageSection extends StatelessWidget {
  final Post post; // Use the Post class generated by freezed

  const ImageSection({super.key, required this.post});

  @override
  Widget build(BuildContext context) {
    return post.media != null && post.media!.isNotEmpty
        ? Container(
            height: 234.0,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(8.0),
              image: DecorationImage(
                image: NetworkImage(post.media!),
                fit: BoxFit.contain,
              ),
            ),
          )
        : const SizedBox.shrink();
  }
}
