// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKR4NT6ITbw2Gxe6G1Ne6eCAjQkUChM_Q',
    appId: '1:644505275007:web:f2e46b8acdac0bfd574d4a',
    messagingSenderId: '644505275007',
    projectId: 'team-sos-3f720',
    authDomain: 'team-sos-3f720.firebaseapp.com',
    storageBucket: 'team-sos-3f720.appspot.com',
    measurementId: 'G-V54WE51QC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBon22A7h0UfQ7Pe0u3sA1H5N_tfm55b6k',
    appId: '1:644505275007:android:c2097a5c8bb33743574d4a',
    messagingSenderId: '644505275007',
    projectId: 'team-sos-3f720',
    storageBucket: 'team-sos-3f720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKjnwouSwBM2_O7EMB-aPsZaNoHYkkpiM',
    appId: '1:644505275007:ios:5781d5151edc4ea6574d4a',
    messagingSenderId: '644505275007',
    projectId: 'team-sos-3f720',
    storageBucket: 'team-sos-3f720.appspot.com',
    iosBundleId: 'com.sos.khu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKjnwouSwBM2_O7EMB-aPsZaNoHYkkpiM',
    appId: '1:644505275007:ios:5781d5151edc4ea6574d4a',
    messagingSenderId: '644505275007',
    projectId: 'team-sos-3f720',
    storageBucket: 'team-sos-3f720.appspot.com',
    iosBundleId: 'com.sos.khu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKR4NT6ITbw2Gxe6G1Ne6eCAjQkUChM_Q',
    appId: '1:644505275007:web:fe98b81ab801bce2574d4a',
    messagingSenderId: '644505275007',
    projectId: 'team-sos-3f720',
    authDomain: 'team-sos-3f720.firebaseapp.com',
    storageBucket: 'team-sos-3f720.appspot.com',
    measurementId: 'G-DMZTJ7RZ93',
  );
}
